#############################################################################
# Makefile for building: bin/qt-fsarchiver
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  qt-fsarchiver.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile qt-fsarchiver.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = x86_64-linux-gnu-gcc
CXX           = x86_64-linux-gnu-g++
DEFINES       = -DHAVE_CONFIG_H -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_GNU_SOURCE -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I. -Isrc -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -Ibuild -Ibuild -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = qt-fsarchiver1.0.0
DISTDIR = /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/qt-fsarchiver1.0.0
LINK          = x86_64-linux-gnu-g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS) -L/usr/lib -lQt5Gui -lQt5Core -lrt -llzma -lext2fs -lcom_err -le2p -lblkid -luuid -lz -llz4 -lbz2 -llzo2 -lgcrypt -lgpg-error -lzstd /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = x86_64-linux-gnu-strip

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/clone.cpp \
		src/dir.cpp \
		src/filedialog.cpp \
		src/main.cc \
		src/mainWindow.cpp \
		src/mbr.cpp \
		src/net.cpp \
		src/net_ein.cpp \
		src/setting.cpp \
		src/thread.cpp \
		src/treeview.cpp build/qrc_icon.cpp \
		build/moc_clone.cpp \
		build/moc_dir.cpp \
		build/moc_filedialog.cpp \
		build/moc_mainWindow.cpp \
		build/moc_mbr.cpp \
		build/moc_net.cpp \
		build/moc_net_ein.cpp \
		build/moc_setting.cpp \
		build/moc_thread.cpp \
		build/moc_treeview.cpp
OBJECTS       = build/clone.o \
		build/dir.o \
		build/filedialog.o \
		build/main.o \
		build/mainWindow.o \
		build/mbr.o \
		build/net.o \
		build/net_ein.o \
		build/setting.o \
		build/thread.o \
		build/treeview.o \
		build/qrc_icon.o \
		build/moc_clone.o \
		build/moc_dir.o \
		build/moc_filedialog.o \
		build/moc_mainWindow.o \
		build/moc_mbr.o \
		build/moc_net.o \
		build/moc_net_ein.o \
		build/moc_setting.o \
		build/moc_thread.o \
		build/moc_treeview.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qt-fsarchiver.pro src/clone.h \
		src/dir.h \
		src/gettext.h \
		src/filedialog.h \
		src/mainWindow.h \
		src/mbr.h \
		src/net.h \
		src/net_ein.h \
		src/setting.h \
		src/thread.h \
		src/treeview.h src/clone.cpp \
		src/dir.cpp \
		src/filedialog.cpp \
		src/main.cc \
		src/mainWindow.cpp \
		src/mbr.cpp \
		src/net.cpp \
		src/net_ein.cpp \
		src/setting.cpp \
		src/thread.cpp \
		src/treeview.cpp
QMAKE_TARGET  = qt-fsarchiver
DESTDIR       = bin/
TARGET        = bin/qt-fsarchiver


first: all
####### Build rules

bin/qt-fsarchiver: qt-fsarchiver_ar.qm qt-fsarchiver_ca.qm qt-fsarchiver_ch.qm qt-fsarchiver_cs.qm qt-fsarchiver_da.qm qt-fsarchiver_de.qm qt-fsarchiver_el.qm qt-fsarchiver_es.qm qt-fsarchiver_et.qm qt-fsarchiver_fa.qm qt-fsarchiver_fi.qm qt-fsarchiver_fr.qm qt-fsarchiver_he.qm qt-fsarchiver_hi.qm qt-fsarchiver_hu.qm qt-fsarchiver_hy.qm qt-fsarchiver_id.qm qt-fsarchiver_it.qm qt-fsarchiver_jp.qm qt-fsarchiver_ko.qm qt-fsarchiver_lt.qm qt-fsarchiver_lv.qm qt-fsarchiver_nl.qm qt-fsarchiver_no.qm qt-fsarchiver_pl.qm qt-fsarchiver_pt.qm qt-fsarchiver_ro.qm qt-fsarchiver_ru.qm qt-fsarchiver_sl.qm qt-fsarchiver_sr.qm qt-fsarchiver_sv.qm qt-fsarchiver_th.qm qt-fsarchiver_tr.qm qt-fsarchiver_uk.qm qt-fsarchiver_ur.qm qt-fsarchiver_vi.qm build/ui_clone_dialog.h build/ui_dir_dialog.h build/ui_filedialog.h build/ui_fsarchiverMain.h build/ui_mbr_dialog.h build/ui_net.h build/ui_net_ein.h build/ui_setting.h build/ui_treeview.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: qt-fsarchiver.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		qt-fsarchiver.pro \
		src/icon.qrc \
		/usr/lib/x86_64-linux-gnu/libQt5Gui.prl \
		/usr/lib/x86_64-linux-gnu/libQt5Core.prl
	$(QMAKE) -o Makefile qt-fsarchiver.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
qt-fsarchiver.pro:
src/icon.qrc:
/usr/lib/x86_64-linux-gnu/libQt5Gui.prl:
/usr/lib/x86_64-linux-gnu/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile qt-fsarchiver.pro -qtconf /usr/lib/x86_64-linux-gnu/qt5/qt.conf -early QMAKE_CC=x86_64-linux-gnu-gcc QMAKE_CXX=x86_64-linux-gnu-g++ QMAKE_LINK=x86_64-linux-gnu-g++ QMAKE_STRIP=x86_64-linux-gnu-strip QMAKE_QMAKE=/usr/bin/x86_64-linux-gnu-qmake PKG_CONFIG=x86_64-linux-gnu-pkg-config -before

qmake_all: FORCE


all: Makefile bin/qt-fsarchiver

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents translations/qt-fsarchiver_ar.ts translations/qt-fsarchiver_ca.ts translations/qt-fsarchiver_ch.ts translations/qt-fsarchiver_cs.ts translations/qt-fsarchiver_da.ts translations/qt-fsarchiver_de.ts translations/qt-fsarchiver_el.ts translations/qt-fsarchiver_es.ts translations/qt-fsarchiver_et.ts translations/qt-fsarchiver_fa.ts translations/qt-fsarchiver_fi.ts translations/qt-fsarchiver_fr.ts translations/qt-fsarchiver_he.ts translations/qt-fsarchiver_hi.ts translations/qt-fsarchiver_hu.ts translations/qt-fsarchiver_hy.ts translations/qt-fsarchiver_id.ts translations/qt-fsarchiver_it.ts translations/qt-fsarchiver_jp.ts translations/qt-fsarchiver_ko.ts translations/qt-fsarchiver_lt.ts translations/qt-fsarchiver_lv.ts translations/qt-fsarchiver_nl.ts translations/qt-fsarchiver_no.ts translations/qt-fsarchiver_pl.ts translations/qt-fsarchiver_pt.ts translations/qt-fsarchiver_ro.ts translations/qt-fsarchiver_ru.ts translations/qt-fsarchiver_sl.ts translations/qt-fsarchiver_sr.ts translations/qt-fsarchiver_sv.ts translations/qt-fsarchiver_th.ts translations/qt-fsarchiver_tr.ts translations/qt-fsarchiver_uk.ts translations/qt-fsarchiver_ur.ts translations/qt-fsarchiver_vi.ts $(DISTDIR)/
	$(COPY_FILE) --parents src/icon.qrc $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/clone.h src/dir.h src/gettext.h src/filedialog.h src/mainWindow.h src/mbr.h src/net.h src/net_ein.h src/setting.h src/thread.h src/treeview.h $(DISTDIR)/
	$(COPY_FILE) --parents src/clone.cpp src/dir.cpp src/filedialog.cpp src/main.cc src/mainWindow.cpp src/mbr.cpp src/net.cpp src/net_ein.cpp src/setting.cpp src/thread.cpp src/treeview.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/ui/clone_dialog.ui src/ui/dir_dialog.ui src/ui/filedialog.ui src/ui/fsarchiverMain.ui src/ui/mbr_dialog.ui src/ui/net.ui src/ui/net_ein.ui src/ui/setting.ui src/ui/treeview.ui $(DISTDIR)/
	$(COPY_FILE) --parents translations/qt-fsarchiver_ar.ts translations/qt-fsarchiver_ca.ts translations/qt-fsarchiver_ch.ts translations/qt-fsarchiver_cs.ts translations/qt-fsarchiver_da.ts translations/qt-fsarchiver_de.ts translations/qt-fsarchiver_el.ts translations/qt-fsarchiver_es.ts translations/qt-fsarchiver_et.ts translations/qt-fsarchiver_fa.ts translations/qt-fsarchiver_fi.ts translations/qt-fsarchiver_fr.ts translations/qt-fsarchiver_he.ts translations/qt-fsarchiver_hi.ts translations/qt-fsarchiver_hu.ts translations/qt-fsarchiver_hy.ts translations/qt-fsarchiver_id.ts translations/qt-fsarchiver_it.ts translations/qt-fsarchiver_jp.ts translations/qt-fsarchiver_ko.ts translations/qt-fsarchiver_lt.ts translations/qt-fsarchiver_lv.ts translations/qt-fsarchiver_nl.ts translations/qt-fsarchiver_no.ts translations/qt-fsarchiver_pl.ts translations/qt-fsarchiver_pt.ts translations/qt-fsarchiver_ro.ts translations/qt-fsarchiver_ru.ts translations/qt-fsarchiver_sl.ts translations/qt-fsarchiver_sr.ts translations/qt-fsarchiver_sv.ts translations/qt-fsarchiver_th.ts translations/qt-fsarchiver_tr.ts translations/qt-fsarchiver_uk.ts translations/qt-fsarchiver_ur.ts translations/qt-fsarchiver_vi.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_lrelease_make_all: qt-fsarchiver_ar.qm qt-fsarchiver_ca.qm qt-fsarchiver_ch.qm qt-fsarchiver_cs.qm qt-fsarchiver_da.qm qt-fsarchiver_de.qm qt-fsarchiver_el.qm qt-fsarchiver_es.qm qt-fsarchiver_et.qm qt-fsarchiver_fa.qm qt-fsarchiver_fi.qm qt-fsarchiver_fr.qm qt-fsarchiver_he.qm qt-fsarchiver_hi.qm qt-fsarchiver_hu.qm qt-fsarchiver_hy.qm qt-fsarchiver_id.qm qt-fsarchiver_it.qm qt-fsarchiver_jp.qm qt-fsarchiver_ko.qm qt-fsarchiver_lt.qm qt-fsarchiver_lv.qm qt-fsarchiver_nl.qm qt-fsarchiver_no.qm qt-fsarchiver_pl.qm qt-fsarchiver_pt.qm qt-fsarchiver_ro.qm qt-fsarchiver_ru.qm qt-fsarchiver_sl.qm qt-fsarchiver_sr.qm qt-fsarchiver_sv.qm qt-fsarchiver_th.qm qt-fsarchiver_tr.qm qt-fsarchiver_uk.qm qt-fsarchiver_ur.qm qt-fsarchiver_vi.qm
compiler_lrelease_clean:
	-$(DEL_FILE) qt-fsarchiver_ar.qm qt-fsarchiver_ca.qm qt-fsarchiver_ch.qm qt-fsarchiver_cs.qm qt-fsarchiver_da.qm qt-fsarchiver_de.qm qt-fsarchiver_el.qm qt-fsarchiver_es.qm qt-fsarchiver_et.qm qt-fsarchiver_fa.qm qt-fsarchiver_fi.qm qt-fsarchiver_fr.qm qt-fsarchiver_he.qm qt-fsarchiver_hi.qm qt-fsarchiver_hu.qm qt-fsarchiver_hy.qm qt-fsarchiver_id.qm qt-fsarchiver_it.qm qt-fsarchiver_jp.qm qt-fsarchiver_ko.qm qt-fsarchiver_lt.qm qt-fsarchiver_lv.qm qt-fsarchiver_nl.qm qt-fsarchiver_no.qm qt-fsarchiver_pl.qm qt-fsarchiver_pt.qm qt-fsarchiver_ro.qm qt-fsarchiver_ru.qm qt-fsarchiver_sl.qm qt-fsarchiver_sr.qm qt-fsarchiver_sv.qm qt-fsarchiver_th.qm qt-fsarchiver_tr.qm qt-fsarchiver_uk.qm qt-fsarchiver_ur.qm qt-fsarchiver_vi.qm
qt-fsarchiver_ar.qm: translations/qt-fsarchiver_ar.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_ar.ts -qm translations/qt-fsarchiver_ar.qm

qt-fsarchiver_ca.qm: translations/qt-fsarchiver_ca.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_ca.ts -qm translations/qt-fsarchiver_ca.qm

qt-fsarchiver_ch.qm: translations/qt-fsarchiver_ch.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_ch.ts -qm translations/qt-fsarchiver_ch.qm

qt-fsarchiver_cs.qm: translations/qt-fsarchiver_cs.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_cs.ts -qm translations/qt-fsarchiver_cs.qm

qt-fsarchiver_da.qm: translations/qt-fsarchiver_da.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_da.ts -qm translations/qt-fsarchiver_da.qm

qt-fsarchiver_de.qm: translations/qt-fsarchiver_de.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_de.ts -qm translations/qt-fsarchiver_de.qm

qt-fsarchiver_el.qm: translations/qt-fsarchiver_el.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_el.ts -qm translations/qt-fsarchiver_el.qm

qt-fsarchiver_es.qm: translations/qt-fsarchiver_es.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_es.ts -qm translations/qt-fsarchiver_es.qm

qt-fsarchiver_et.qm: translations/qt-fsarchiver_et.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_et.ts -qm translations/qt-fsarchiver_et.qm

qt-fsarchiver_fa.qm: translations/qt-fsarchiver_fa.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_fa.ts -qm translations/qt-fsarchiver_fa.qm

qt-fsarchiver_fi.qm: translations/qt-fsarchiver_fi.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_fi.ts -qm translations/qt-fsarchiver_fi.qm

qt-fsarchiver_fr.qm: translations/qt-fsarchiver_fr.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_fr.ts -qm translations/qt-fsarchiver_fr.qm

qt-fsarchiver_he.qm: translations/qt-fsarchiver_he.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_he.ts -qm translations/qt-fsarchiver_he.qm

qt-fsarchiver_hi.qm: translations/qt-fsarchiver_hi.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_hi.ts -qm translations/qt-fsarchiver_hi.qm

qt-fsarchiver_hu.qm: translations/qt-fsarchiver_hu.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_hu.ts -qm translations/qt-fsarchiver_hu.qm

qt-fsarchiver_hy.qm: translations/qt-fsarchiver_hy.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_hy.ts -qm translations/qt-fsarchiver_hy.qm

qt-fsarchiver_id.qm: translations/qt-fsarchiver_id.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_id.ts -qm translations/qt-fsarchiver_id.qm

qt-fsarchiver_it.qm: translations/qt-fsarchiver_it.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_it.ts -qm translations/qt-fsarchiver_it.qm

qt-fsarchiver_jp.qm: translations/qt-fsarchiver_jp.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_jp.ts -qm translations/qt-fsarchiver_jp.qm

qt-fsarchiver_ko.qm: translations/qt-fsarchiver_ko.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_ko.ts -qm translations/qt-fsarchiver_ko.qm

qt-fsarchiver_lt.qm: translations/qt-fsarchiver_lt.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_lt.ts -qm translations/qt-fsarchiver_lt.qm

qt-fsarchiver_lv.qm: translations/qt-fsarchiver_lv.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_lv.ts -qm translations/qt-fsarchiver_lv.qm

qt-fsarchiver_nl.qm: translations/qt-fsarchiver_nl.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_nl.ts -qm translations/qt-fsarchiver_nl.qm

qt-fsarchiver_no.qm: translations/qt-fsarchiver_no.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_no.ts -qm translations/qt-fsarchiver_no.qm

qt-fsarchiver_pl.qm: translations/qt-fsarchiver_pl.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_pl.ts -qm translations/qt-fsarchiver_pl.qm

qt-fsarchiver_pt.qm: translations/qt-fsarchiver_pt.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_pt.ts -qm translations/qt-fsarchiver_pt.qm

qt-fsarchiver_ro.qm: translations/qt-fsarchiver_ro.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_ro.ts -qm translations/qt-fsarchiver_ro.qm

qt-fsarchiver_ru.qm: translations/qt-fsarchiver_ru.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_ru.ts -qm translations/qt-fsarchiver_ru.qm

qt-fsarchiver_sl.qm: translations/qt-fsarchiver_sl.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_sl.ts -qm translations/qt-fsarchiver_sl.qm

qt-fsarchiver_sr.qm: translations/qt-fsarchiver_sr.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_sr.ts -qm translations/qt-fsarchiver_sr.qm

qt-fsarchiver_sv.qm: translations/qt-fsarchiver_sv.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_sv.ts -qm translations/qt-fsarchiver_sv.qm

qt-fsarchiver_th.qm: translations/qt-fsarchiver_th.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_th.ts -qm translations/qt-fsarchiver_th.qm

qt-fsarchiver_tr.qm: translations/qt-fsarchiver_tr.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_tr.ts -qm translations/qt-fsarchiver_tr.qm

qt-fsarchiver_uk.qm: translations/qt-fsarchiver_uk.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_uk.ts -qm translations/qt-fsarchiver_uk.qm

qt-fsarchiver_ur.qm: translations/qt-fsarchiver_ur.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_ur.ts -qm translations/qt-fsarchiver_ur.qm

qt-fsarchiver_vi.qm: translations/qt-fsarchiver_vi.ts
	/usr/lib/qt5/bin/lrelease translations/qt-fsarchiver_vi.ts -qm translations/qt-fsarchiver_vi.qm

compiler_rcc_make_all: build/qrc_icon.cpp
compiler_rcc_clean:
	-$(DEL_FILE) build/qrc_icon.cpp
build/qrc_icon.cpp: src/icon.qrc \
		/usr/lib/qt5/bin/rcc \
		src/images/einstellung.png \
		src/images/folder_go.png \
		src/images/book_previous.png \
		src/images/applications-internet.png \
		src/images/dir.png \
		src/images/mbr_save.png \
		src/images/file.png \
		src/images/folder_back.png \
		src/images/information.png \
		src/images/folder_page_white.png \
		src/images/cdtoparent.png \
		src/images/cancel.png \
		src/images/setting.png \
		src/images/mbr_restore.png \
		src/images/disk.png \
		src/images/clone1.png \
		src/images/applications-internet-ein.png
	/usr/lib/qt5/bin/rcc -name icon src/icon.qrc -o build/qrc_icon.cpp

compiler_moc_predefs_make_all: build/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) build/moc_predefs.h
build/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	x86_64-linux-gnu-g++ -pipe -O2 -Wall -Wextra -dM -E -o build/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: build/moc_clone.cpp build/moc_dir.cpp build/moc_filedialog.cpp build/moc_mainWindow.cpp build/moc_mbr.cpp build/moc_net.cpp build/moc_net_ein.cpp build/moc_setting.cpp build/moc_thread.cpp build/moc_treeview.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_clone.cpp build/moc_dir.cpp build/moc_filedialog.cpp build/moc_mainWindow.cpp build/moc_mbr.cpp build/moc_net.cpp build/moc_net_ein.cpp build/moc_setting.cpp build/moc_thread.cpp build/moc_treeview.cpp
build/moc_clone.cpp: src/clone.h \
		build/ui_clone_dialog.h \
		src/thread.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/clone.h -o build/moc_clone.cpp

build/moc_dir.cpp: src/dir.h \
		build/ui_dir_dialog.h \
		src/thread.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/dir.h -o build/moc_dir.cpp

build/moc_filedialog.cpp: src/filedialog.h \
		build/ui_filedialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/filedialog.h -o build/moc_filedialog.cpp

build/moc_mainWindow.cpp: src/mainWindow.h \
		build/ui_fsarchiverMain.h \
		src/thread.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mainWindow.h -o build/moc_mainWindow.cpp

build/moc_mbr.cpp: src/mbr.h \
		build/ui_mbr_dialog.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/mbr.h -o build/moc_mbr.cpp

build/moc_net.cpp: src/net.h \
		build/ui_net.h \
		src/thread.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/net.h -o build/moc_net.cpp

build/moc_net_ein.cpp: src/net_ein.h \
		build/ui_net_ein.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/net_ein.h -o build/moc_net_ein.cpp

build/moc_setting.cpp: src/setting.h \
		build/ui_setting.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/setting.h -o build/moc_setting.cpp

build/moc_thread.cpp: src/thread.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/thread.h -o build/moc_thread.cpp

build/moc_treeview.cpp: src/treeview.h \
		build/ui_treeview.h \
		build/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/hamonikr/workspaces/tmp/qt-fsarchiver/build/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver -I/home/hamonikr/workspaces/tmp/qt-fsarchiver/src -I/usr/include/ext2fs -I/usr/include/et -I/usr/include/e2p -I/usr/include/blkid -I/usr/include/uuid -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/9 -I/usr/include/x86_64-linux-gnu/c++/9 -I/usr/include/c++/9/backward -I/usr/lib/gcc/x86_64-linux-gnu/9/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/treeview.h -o build/moc_treeview.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_clone_dialog.h build/ui_dir_dialog.h build/ui_filedialog.h build/ui_fsarchiverMain.h build/ui_mbr_dialog.h build/ui_net.h build/ui_net_ein.h build/ui_setting.h build/ui_treeview.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_clone_dialog.h build/ui_dir_dialog.h build/ui_filedialog.h build/ui_fsarchiverMain.h build/ui_mbr_dialog.h build/ui_net.h build/ui_net_ein.h build/ui_setting.h build/ui_treeview.h
build/ui_clone_dialog.h: src/ui/clone_dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/clone_dialog.ui -o build/ui_clone_dialog.h

build/ui_dir_dialog.h: src/ui/dir_dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/dir_dialog.ui -o build/ui_dir_dialog.h

build/ui_filedialog.h: src/ui/filedialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/filedialog.ui -o build/ui_filedialog.h

build/ui_fsarchiverMain.h: src/ui/fsarchiverMain.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/fsarchiverMain.ui -o build/ui_fsarchiverMain.h

build/ui_mbr_dialog.h: src/ui/mbr_dialog.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/mbr_dialog.ui -o build/ui_mbr_dialog.h

build/ui_net.h: src/ui/net.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/net.ui -o build/ui_net.h

build/ui_net_ein.h: src/ui/net_ein.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/net_ein.ui -o build/ui_net_ein.h

build/ui_setting.h: src/ui/setting.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/setting.ui -o build/ui_setting.h

build/ui_treeview.h: src/ui/treeview.ui \
		/usr/lib/qt5/bin/uic
	/usr/lib/qt5/bin/uic src/ui/treeview.ui -o build/ui_treeview.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_lrelease_clean compiler_rcc_clean compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

build/clone.o: src/clone.cpp src/clone.h \
		build/ui_clone_dialog.h \
		src/thread.h \
		src/mainWindow.h \
		build/ui_fsarchiverMain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/clone.o src/clone.cpp

build/dir.o: src/dir.cpp src/dir.h \
		build/ui_dir_dialog.h \
		src/thread.h \
		src/mainWindow.h \
		build/ui_fsarchiverMain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/dir.o src/dir.cpp

build/filedialog.o: src/filedialog.cpp src/filedialog.h \
		build/ui_filedialog.h \
		src/mainWindow.h \
		build/ui_fsarchiverMain.h \
		src/thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/filedialog.o src/filedialog.cpp

build/main.o: src/main.cc src/mainWindow.h \
		build/ui_fsarchiverMain.h \
		src/thread.h \
		src/setting.h \
		build/ui_setting.h \
		src/gettext.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cc

build/mainWindow.o: src/mainWindow.cpp src/mainWindow.h \
		build/ui_fsarchiverMain.h \
		src/thread.h \
		src/filedialog.h \
		build/ui_filedialog.h \
		src/setting.h \
		build/ui_setting.h \
		src/net.h \
		build/ui_net.h \
		src/net_ein.h \
		build/ui_net_ein.h \
		src/mbr.h \
		build/ui_mbr_dialog.h \
		src/clone.h \
		build/ui_clone_dialog.h \
		src/dir.h \
		build/ui_dir_dialog.h \
		src/treeview.h \
		build/ui_treeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mainWindow.o src/mainWindow.cpp

build/mbr.o: src/mbr.cpp src/mbr.h \
		build/ui_mbr_dialog.h \
		src/thread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/mbr.o src/mbr.cpp

build/net.o: src/net.cpp src/net.h \
		build/ui_net.h \
		src/thread.h \
		src/net_ein.h \
		build/ui_net_ein.h \
		src/filedialog.h \
		build/ui_filedialog.h \
		src/mainWindow.h \
		build/ui_fsarchiverMain.h \
		src/treeview.h \
		build/ui_treeview.h \
		src/setting.h \
		build/ui_setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/net.o src/net.cpp

build/net_ein.o: src/net_ein.cpp src/net_ein.h \
		build/ui_net_ein.h \
		src/net.h \
		build/ui_net.h \
		src/thread.h \
		src/mainWindow.h \
		build/ui_fsarchiverMain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/net_ein.o src/net_ein.cpp

build/setting.o: src/setting.cpp src/setting.h \
		build/ui_setting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/setting.o src/setting.cpp

build/thread.o: src/thread.cpp src/thread.h \
		src/mainWindow.h \
		build/ui_fsarchiverMain.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/thread.o src/thread.cpp

build/treeview.o: src/treeview.cpp src/treeview.h \
		build/ui_treeview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/treeview.o src/treeview.cpp

build/qrc_icon.o: build/qrc_icon.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_icon.o build/qrc_icon.cpp

build/moc_clone.o: build/moc_clone.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_clone.o build/moc_clone.cpp

build/moc_dir.o: build/moc_dir.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_dir.o build/moc_dir.cpp

build/moc_filedialog.o: build/moc_filedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_filedialog.o build/moc_filedialog.cpp

build/moc_mainWindow.o: build/moc_mainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mainWindow.o build/moc_mainWindow.cpp

build/moc_mbr.o: build/moc_mbr.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_mbr.o build/moc_mbr.cpp

build/moc_net.o: build/moc_net.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_net.o build/moc_net.cpp

build/moc_net_ein.o: build/moc_net_ein.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_net_ein.o build/moc_net_ein.cpp

build/moc_setting.o: build/moc_setting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_setting.o build/moc_setting.cpp

build/moc_thread.o: build/moc_thread.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_thread.o build/moc_thread.cpp

build/moc_treeview.o: build/moc_treeview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_treeview.o build/moc_treeview.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/sbin || mkdir -p $(INSTALL_ROOT)/usr/sbin
	$(QINSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/usr/sbin/$(QMAKE_TARGET)
	-$(STRIP) $(INSTALL_ROOT)/usr/sbin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/sbin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/sbin/ 


install_icon: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/app-install/icons || mkdir -p $(INSTALL_ROOT)/usr/share/app-install/icons
	$(QINSTALL_PROGRAM) /home/hamonikr/workspaces/tmp/qt-fsarchiver/src/images/harddrive2.png $(INSTALL_ROOT)/usr/share/app-install/icons/harddrive2.png
	-x86_64-linux-gnu-strip $(INSTALL_ROOT)/usr/share/app-install/icons/harddrive2.png

uninstall_icon: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/app-install/icons/harddrive2.png
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/app-install/icons/ 


install_autostart: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/applications || mkdir -p $(INSTALL_ROOT)/usr/share/applications
	$(QINSTALL_PROGRAM) /home/hamonikr/workspaces/tmp/qt-fsarchiver/starter/qt-fsarchiver.desktop $(INSTALL_ROOT)/usr/share/applications/qt-fsarchiver.desktop
	-x86_64-linux-gnu-strip $(INSTALL_ROOT)/usr/share/applications/qt-fsarchiver.desktop

uninstall_autostart: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/applications/qt-fsarchiver.desktop
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/applications/ 


install_translations: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/qt5/translations || mkdir -p $(INSTALL_ROOT)/usr/share/qt5/translations
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_de.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_de.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_es.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_es.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_ru.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ru.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_nl.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_nl.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_id.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_id.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_it.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_it.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_ch.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ch.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_cs.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_cs.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_jp.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_jp.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_ar.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ar.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_ca.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ca.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_da.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_da.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_el.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_el.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_et.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_et.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_fa.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_fa.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_fi.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_fi.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_fr.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_fr.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_he.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_he.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_hi.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_hi.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_hu.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_hu.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_hy.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_hy.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_ko.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ko.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_lv.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_lv.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_lt.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_lt.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_no.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_no.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_pl.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_pl.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_pt.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_pt.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_ro.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ro.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_sl.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_sl.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_sr.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_sr.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_sv.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_sv.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_th.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_th.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_tr.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_tr.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_vi.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_vi.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_ur.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ur.qm
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/translations/qt-fsarchiver_uk.qm $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_uk.qm

uninstall_translations: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_uk.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ur.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_vi.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_tr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_th.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_sv.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_sr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_sl.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ro.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_pt.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_pl.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_no.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_lt.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_lv.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ko.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_hy.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_hu.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_hi.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_he.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_fr.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_fi.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_fa.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_et.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_el.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_da.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ca.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ar.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_jp.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_cs.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ch.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_it.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_id.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_nl.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_ru.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_es.qm
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/qt5/translations/qt-fsarchiver_de.qm
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/qt5/translations/ 


install_doc: first FORCE
	@test -d $(INSTALL_ROOT)/usr/share/doc/qt-fsarchiver/doc || mkdir -p $(INSTALL_ROOT)/usr/share/doc/qt-fsarchiver/doc
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/doc $(INSTALL_ROOT)/usr/share/doc/qt-fsarchiver/doc/doc

uninstall_doc: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/share/doc/qt-fsarchiver/doc/doc
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/share/doc/qt-fsarchiver/doc/ 


install_smbfind: first FORCE
	@test -d $(INSTALL_ROOT)/usr || mkdir -p $(INSTALL_ROOT)/usr
	$(QINSTALL) /home/hamonikr/workspaces/tmp/qt-fsarchiver/src/sbin $(INSTALL_ROOT)/usr/sbin

uninstall_smbfind: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/usr/sbin
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/ 


install: install_target install_icon install_autostart install_translations install_doc install_smbfind  FORCE

uninstall: uninstall_target uninstall_icon uninstall_autostart uninstall_translations uninstall_doc uninstall_smbfind  FORCE

FORCE:

